sudo: required
services:
 - docker

before_install:
 - docker build -t abeleshev/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run abeleshev/react-test npm test -- --coverage

after_success:
 - docker build -t abeleshev/multi-client ./client
 - docker build -t abeleshev/multi-nginx ./nginx
 - docker build -t abeleshev/multi-server ./server
 - docker build -t abeleshev/multi-worker ./worker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push abeleshev/multi-client
 - docker push abeleshev/multi-nginx
 - docker push abeleshev/multi-server
 - docker push abeleshev/multi-worker
